package server

import (
	"encoding/json"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/stockyard-dev/stockyard-dossier/internal/store"
)

// resourceName is the canonical key used in the API path and the extras table.
// Dossier stores contacts, so all extras are scoped under "contacts".
const resourceName = "contacts"

type Server struct {
	db      *store.DB
	mux     *http.ServeMux
	limMu   sync.RWMutex // guards limits, which can be hot-reloaded by /api/license/activate
	limits  Limits
	dataDir string
	pCfg    map[string]json.RawMessage // personalization config from config.json
}

// New constructs the server. dataDir is used to look for config.json
// (the personalization payload generated by the Stockyard AI toolkit builder).
func New(db *store.DB, limits Limits, dataDir string) *Server {
	s := &Server{
		db:      db,
		mux:     http.NewServeMux(),
		limits:  limits,
		dataDir: dataDir,
	}
	s.loadPersonalConfig()

	// Contact CRUD
	s.mux.HandleFunc("GET /api/contacts", s.list)
	s.mux.HandleFunc("POST /api/contacts", s.create)
	s.mux.HandleFunc("GET /api/contacts/{id}", s.get)
	s.mux.HandleFunc("PUT /api/contacts/{id}", s.update)
	s.mux.HandleFunc("DELETE /api/contacts/{id}", s.del)

	// Stats and health
	s.mux.HandleFunc("GET /api/stats", s.stats)
	s.mux.HandleFunc("GET /api/health", s.health)

	// Personalization
	s.mux.HandleFunc("GET /api/config", s.configHandler)

	// Extras (custom fields injected by personalization)
	s.mux.HandleFunc("GET /api/extras/{resource}", s.listExtras)
	s.mux.HandleFunc("GET /api/extras/{resource}/{id}", s.getExtras)
	s.mux.HandleFunc("PUT /api/extras/{resource}/{id}", s.putExtras)

	// CSV import — two-step preview/commit flow. See import.go for the
	// rationale on splitting these into separate endpoints instead of a
	// single upload-and-import call. Preview is read-only and allowed
	// during trial-required mode; commit is a write and is gated.
	s.mux.HandleFunc("POST /api/import/preview", s.previewImport)
	s.mux.HandleFunc("POST /api/import/commit", s.commitImport)

	// License activation — accepts a key, validates it, persists to
	// dataDir/license.txt, and hot-reloads s.limits so the next request
	// sees the new tier without a restart.
	s.mux.HandleFunc("POST /api/license/activate", s.activateLicense)

	// Dashboard and root
	s.mux.HandleFunc("GET /ui", s.dashboard)
	s.mux.HandleFunc("GET /ui/", s.dashboard)
	s.mux.HandleFunc("GET /", s.root)

	// Tier (license) info — read-only, returns current tier + a hint
	// for the dashboard banner. Always reachable so the frontend can
	// detect trial-required state on first load.
	s.mux.HandleFunc("GET /api/tier", s.tierInfo)

	return s
}

// ServeHTTP wraps the underlying mux with a license-gate middleware.
// In trial-required mode, all writes (POST/PUT/DELETE/PATCH) return 402
// EXCEPT the explicit allowlist of routes the trial UX needs to function:
//   - POST /api/license/activate (the only way out of trial-required state)
//   - POST /api/import/preview   (read-only — lets prospects see what
//     import would do before deciding to subscribe)
//
// Reads are always allowed in trial-required mode so customers who lost
// their license key can still see their existing data, which is the
// fundamental brand promise ("your data stays on your machine forever").
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if s.shouldBlockWrite(r) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusPaymentRequired)
		w.Write([]byte(`{"error":"Trial required. Start a 14-day free trial at https://stockyard.dev/ — or paste an existing license key in the dashboard under \"Activate License\".","tier":"trial-required"}`))
		return
	}
	s.mux.ServeHTTP(w, r)
}

// shouldBlockWrite returns true when the current tier is trial-required
// AND the incoming request is a non-allowlisted write.
func (s *Server) shouldBlockWrite(r *http.Request) bool {
	s.limMu.RLock()
	tier := s.limits.Tier
	s.limMu.RUnlock()
	if tier != "trial-required" {
		return false
	}
	// Reads always allowed
	switch r.Method {
	case http.MethodGet, http.MethodHead, http.MethodOptions:
		return false
	}
	// Explicit allowlist of writes that must work even without a license
	switch r.URL.Path {
	case "/api/license/activate", "/api/import/preview":
		return false
	}
	return true
}

// activateLicense accepts {license_key: "SY-..."}, validates the key
// using the same Ed25519 logic the boot path uses, persists it to
// dataDir/license.txt, and hot-reloads s.limits so subsequent requests
// see the new tier without a restart.
func (s *Server) activateLicense(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(io.LimitReader(r.Body, 10*1024)) // license keys are ~250 bytes; 10KB is safety margin
	if err != nil {
		we(w, 400, "could not read request body")
		return
	}
	var req struct {
		LicenseKey string `json:"license_key"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		we(w, 400, "invalid json: "+err.Error())
		return
	}
	key := strings.TrimSpace(req.LicenseKey)
	if key == "" {
		we(w, 400, "license_key is required")
		return
	}
	if !ValidateLicenseKey(key) {
		we(w, 400, "license key is not valid for this product — make sure you copied the entire key from the welcome email, including the SY- prefix")
		return
	}
	if err := PersistLicense(s.dataDir, key); err != nil {
		log.Printf("dossier: license persist failed: %v", err)
		we(w, 500, "could not save the license key to disk: "+err.Error())
		return
	}
	s.limMu.Lock()
	s.limits = ProLimits()
	s.limMu.Unlock()
	log.Printf("dossier: license activated via dashboard, persisted to %s/%s", s.dataDir, licenseFilename)
	wj(w, 200, map[string]any{
		"ok":   true,
		"tier": "pro",
	})
}

// tierInfo returns the current tier and a hint for the dashboard banner.
// Always available, never gated, so the frontend can detect trial state
// on first load and decide whether to show the activate banner.
func (s *Server) tierInfo(w http.ResponseWriter, r *http.Request) {
	s.limMu.RLock()
	tier := s.limits.Tier
	s.limMu.RUnlock()
	resp := map[string]any{
		"tier": tier,
	}
	if tier == "trial-required" {
		resp["trial_required"] = true
		resp["start_trial_url"] = "https://stockyard.dev/"
		resp["message"] = "Your trial is not active. Reads work, but you cannot add or change records until you start a 14-day trial or activate an existing license key."
	} else {
		resp["trial_required"] = false
	}
	wj(w, 200, resp)
}

// ─── helpers ──────────────────────────────────────────────────────

func wj(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	json.NewEncoder(w).Encode(v)
}

func we(w http.ResponseWriter, code int, msg string) {
	wj(w, code, map[string]string{"error": msg})
}

func oe[T any](s []T) []T {
	if s == nil {
		return []T{}
	}
	return s
}

func (s *Server) root(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	http.Redirect(w, r, "/ui", 302)
}

// ─── personalization config ───────────────────────────────────────

// loadPersonalConfig reads config.json from the data directory.
// This file is generated by the Stockyard AI toolkit builder and contains
// dashboard title, custom fields, placeholder names, etc.
// Missing or malformed configs are ignored — the tool falls back to defaults.
func (s *Server) loadPersonalConfig() {
	path := filepath.Join(s.dataDir, "config.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var cfg map[string]json.RawMessage
	if err := json.Unmarshal(data, &cfg); err != nil {
		log.Printf("dossier: warning: could not parse config.json: %v", err)
		return
	}
	s.pCfg = cfg
	log.Printf("dossier: loaded personalization from %s", path)
}

func (s *Server) configHandler(w http.ResponseWriter, r *http.Request) {
	if s.pCfg == nil {
		wj(w, 200, map[string]any{})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(s.pCfg)
}

// ─── extras (custom field persistence) ────────────────────────────

// listExtras returns all extras for a resource as {record_id: {...fields...}}
// so the dashboard can merge them into the records on a single fetch.
func (s *Server) listExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	all := s.db.AllExtras(resource)
	out := make(map[string]json.RawMessage, len(all))
	for id, data := range all {
		out[id] = json.RawMessage(data)
	}
	wj(w, 200, out)
}

func (s *Server) getExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	id := r.PathValue("id")
	data := s.db.GetExtras(resource, id)
	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(data))
}

func (s *Server) putExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	id := r.PathValue("id")
	body, err := io.ReadAll(r.Body)
	if err != nil {
		we(w, 400, "read body")
		return
	}
	// Validate the body is JSON before storing.
	var probe map[string]any
	if err := json.Unmarshal(body, &probe); err != nil {
		we(w, 400, "invalid json")
		return
	}
	if err := s.db.SetExtras(resource, id, string(body)); err != nil {
		we(w, 500, "save failed")
		return
	}
	wj(w, 200, map[string]string{"ok": "saved"})
}

// ─── contact CRUD ─────────────────────────────────────────────────

func (s *Server) list(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	filters := map[string]string{}
	if v := r.URL.Query().Get("status"); v != "" {
		filters["status"] = v
	}
	if q != "" || len(filters) > 0 {
		wj(w, 200, map[string]any{"contacts": oe(s.db.Search(q, filters))})
		return
	}
	wj(w, 200, map[string]any{"contacts": oe(s.db.List())})
}

func (s *Server) create(w http.ResponseWriter, r *http.Request) {
	// Trial-required gating happens upstream in ServeHTTP middleware,
	// so by the time a POST reaches this handler the caller is licensed.
	// The old item-count cap has been removed — Stockyard does not have
	// a free tier, only a $7.99/mo subscription with a 14-day paid trial.
	var e store.Contact
	if err := json.NewDecoder(r.Body).Decode(&e); err != nil {
		we(w, 400, "invalid json")
		return
	}
	if e.Name == "" {
		we(w, 400, "name required")
		return
	}
	if err := s.db.Create(&e); err != nil {
		we(w, 500, "create failed")
		return
	}
	wj(w, 201, s.db.Get(e.ID))
}

func (s *Server) get(w http.ResponseWriter, r *http.Request) {
	e := s.db.Get(r.PathValue("id"))
	if e == nil {
		we(w, 404, "not found")
		return
	}
	wj(w, 200, e)
}

func (s *Server) update(w http.ResponseWriter, r *http.Request) {
	existing := s.db.Get(r.PathValue("id"))
	if existing == nil {
		we(w, 404, "not found")
		return
	}
	var patch store.Contact
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		we(w, 400, "invalid json")
		return
	}
	patch.ID = existing.ID
	patch.CreatedAt = existing.CreatedAt
	// Preserve unset fields from the existing record (PATCH-style behavior).
	if patch.Name == "" {
		patch.Name = existing.Name
	}
	if patch.Email == "" {
		patch.Email = existing.Email
	}
	if patch.Phone == "" {
		patch.Phone = existing.Phone
	}
	if patch.Company == "" {
		patch.Company = existing.Company
	}
	if patch.Title == "" {
		patch.Title = existing.Title
	}
	if patch.Tags == "" {
		patch.Tags = existing.Tags
	}
	if patch.Notes == "" {
		patch.Notes = existing.Notes
	}
	if patch.Status == "" {
		patch.Status = existing.Status
	}
	if err := s.db.Update(&patch); err != nil {
		we(w, 500, "update failed")
		return
	}
	wj(w, 200, s.db.Get(patch.ID))
}

func (s *Server) del(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	s.db.Delete(id)
	// Cascade: clean up any extras tied to this contact.
	s.db.DeleteExtras(resourceName, id)
	wj(w, 200, map[string]string{"deleted": "ok"})
}

// ─── stats / health ───────────────────────────────────────────────

func (s *Server) stats(w http.ResponseWriter, r *http.Request) {
	wj(w, 200, s.db.Stats())
}

func (s *Server) health(w http.ResponseWriter, r *http.Request) {
	wj(w, 200, map[string]any{
		"status":   "ok",
		"service":  "dossier",
		"contacts": s.db.Count(),
	})
}

func init() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}
